### ISSUE TITLE
Kinda lame error when no creds are found.

### ISSUE THREAD

**Issue by harold** [techascent/tech.io.azure#1]
When no creds are in the env or config or anywhere, this piece of code throws:

https://github.com/techascent/tech.io.azure/blob/master/src/tech/io/azure/blob.clj#L19-L24

![image](https://user-images.githubusercontent.com/7443/62390767-4d2ebb80-b520-11e9-8b57-b7acd2000ab7.png)

Might be nice to catch this and throw a nicer `ex-info` with a message indicating some ways to provide the creds (env, config, or in options map)

**Comment by cnuernber** [comment]
Changed to:
```console
Execution error (ExceptionInfo) at tech.io.azure.blob/opts->client (blob.clj:48).
Could not find account name (null) or account key null
Consider setting environment variables AZURE_BLOB_ACCOUNT_NAME and AZURE_BLOB_ACCOUNT_KEY
```
